export type CaseRecord={partNo:string;devId:string;issue:string;rootCause:string;decision:'CONDITIONAL_REUSE'|'BATCH_ONLY'|'REJECTED'|'MISSING_EVIDENCE';status:string;lessonCode:string;supplier:string;customer:string;year:string;date:string;action:string;conclusion:string;lesson:string;scope:string;verification:string;evidence:string[];history:string[]};
export const cases:CaseRecord[]=[
{partNo:'70196-03',devId:'DEV260119',issue:'Crack',rootCause:'Crack',decision:'CONDITIONAL_REUSE',status:'REUSABLE WITH CONDITIONS',lessonCode:'LL-00017',supplier:'Dong Tam',customer:'DC',year:'2025',date:'17 Jan 25',action:'Ordered new punch, consulted DC team, accepted slight rotation after function review.',conclusion:'Accepted current slight rotation condition for tested lot.',lesson:'Accept slight rotation only when staking joint does not crack and function is proven.',scope:'Similar staking conditions and low-light force valves.',verification:'Staking trial, crack inspection, function check.',evidence:['DEV260119-001_Accept slightly rotate for 70196-03.pdf','DEV260119-001_Accept slightly rotate for 70196-03.docx'],history:['Created by Dong Tam','Reviewed by James','Approved as conditional reuse']},
{partNo:'54101-09',devId:'DEV260306',issue:'Terminal thickness exceeds specification',rootCause:'Dimension out of specification',decision:'CONDITIONAL_REUSE',status:'REUSABLE WITH CONDITIONS',lessonCode:'LL-00045',supplier:'Dong Tam',customer:'DC',year:'2026',date:'06 Mar 26',action:'Fit test, crack inspection, pull force test.',conclusion:'Accepted for approved lot only.',lesson:'Accept only after confirming no crack and pull force greater than 10 lbf.',scope:'Approved lot and directly tested bobbins only.',verification:'Pull force, fit test and crack inspection.',evidence:['NCR_TERMINAL_THICKNESS.xlsx','Dimension_Image.png','Source_Word.docx'],history:['Imported from Excel','Engineer requested evidence','Approved with conditions']},
{partNo:'53180-09',devId:'DEV250414',issue:'Terminal out of spec',rootCause:'Process drift',decision:'BATCH_ONLY',status:'TEMPORARY / LOT-SPECIFIC',lessonCode:'LL-00012',supplier:'FPC',customer:'DC',year:'2025',date:'14 Apr 25',action:'Sorted affected batch and verified terminal stack.',conclusion:'Use only for documented lot.',lesson:'Do not reuse beyond lot without new verification.',scope:'Temporary batch-only acceptance.',verification:'Lot traceability and dimension report.',evidence:['DEV250414_Report.pdf'],history:['Temporary decision','Lot-specific approval']},
{partNo:'88210-01',devId:'DEV260411',issue:'Missing dimensional evidence',rootCause:'Missing evidence',decision:'MISSING_EVIDENCE',status:'MISSING EVIDENCE',lessonCode:'LL-00051',supplier:'ACME',customer:'DC',year:'2026',date:'11 Apr 26',action:'Hold case until evidence folder is complete.',conclusion:'Needs review.',lesson:'Evidence index is required before reuse decision.',scope:'Not reusable yet.',verification:'Upload source Word, PDF and measurement photo.',evidence:[],history:['Imported without PDF','Flagged missing evidence']},
{partNo:'44200-22',devId:'DEV260512',issue:'Wrong color knob',rootCause:'Supplier mix-up',decision:'REJECTED',status:'REJECTED',lessonCode:'LL-00061',supplier:'Supplier B',customer:'DC',year:'2026',date:'12 May 26',action:'Rejected batch and requested replacement.',conclusion:'Not reusable.',lesson:'Color mismatch cannot be reused when customer-facing.',scope:'Rejected cases only.',verification:'Supplier corrective action required.',evidence:['Color_Mismatch.pdf'],history:['Rejected by reviewer']}
];
export function byPart(partNo:string){return cases.filter(c=>c.partNo===partNo)}
export function uniqueParts(){return Array.from(new Set(cases.map(c=>c.partNo))).map(p=>cases.find(c=>c.partNo===p)!)}
